version : '3'

services:
  api01:
    build: ./adminapi
    environment:
      MESSAGE: ${MESSAGE1}
    ports:
      - 8000:3000

  api02:
    build: ./adminapi
    environment:
      MESSAGE: ${MESSAGE2}
    ports:
      - 8001:3000

  api03:
    build: ./adminapi
    environment:
      MESSAGE: ${MESSAGE3}
    ports:
      - 8002:3000

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
